name: Trigger Cloudtype Deploy on Schedule

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes (reliable minimum)
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: peter-evans/workflow-dispatch@v2
        with:
          workflow: Deploy to cloudtype # Must match the `name:` in deploy-main.yml
          ref: main
