name: Dev Deployment

on:
  schedule:
    # 서버가 3시부터 9시까지 중지 되므로, 그 시간대에만 10분마다 배포
    - cron: '*/10 3-9 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-server:
    name: cultpick-server-dev Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          project: aptheparker/free
          stage: main
          yaml: >
            name: cultpick-server-dev

            app: node@22

            options:
              env:
                - name: DATABASE_URL
                  value: ${{ secrets.DATABASE_URL }}
                - name: OPEN_API_URL
                  value: ${{ secrets.OPEN_API_URL }}
                - name: SERVICE_KEY
                  value: ${{ secrets.SERVICE_KEY }}
                - name: PORT
                  value: "3001"
                - name: SMTP_USER
                  value: ${{ secrets.SMTP_USER }}
                - name: SMTP_PASSWORD
                  value: ${{ secrets.SMTP_PASSWORD }}
                - name: ACCESS_TOKEN_SECRET
                  value: ${{ secrets.ACCESS_TOKEN_SECRET }}
                - name: VERIFICATION_TOKEN_SECRET
                  value: ${{ secrets.VERIFICATION_TOKEN_SECRET }}
              ports: "3001"
              build: pnpm prisma generate && pnpm build
              start: pnpm start:prod
              install: pnpm i
              buildenv: []

            context:
              git:
                url: https://github.com/${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: nest.js

  deploy-db:
    name: cultpick-db-dev Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          project: aptheparker/free
          stage: main
          yaml: |
            name: cultpick-db-dev

            app: postgresql@16

            options:
              rootusername: root
              rootpassword: ${{ secrets.DB_ROOT_PASSWORD }}
              database: cultpick

            context:
              preset: postgresql
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
