name: CloudType Deployment

on:
  schedule:
    - cron: '0 0 * * *' # 00:00 Every day
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          project: aptheparker/aptheparker
          stage: main
          yaml: >
            name: cultpick-server-dev

            app: node@22

            options:
              env:
                - name: DATABASE_URL
                  value: postgresql://root:cultpick2025@svc.sel4.cloudtype.app:31843/postgres
                - name: OPEN_API_URL
                  value: http://www.kopis.or.kr/openApi/restful
                - name: SERVICE_KEY
                  value: fc207504c94344cbbcf5560aa110ec7f
                - name: PORT
                  value: "3001"
                - name: SMTP_USER
                  value: culpick@gmail.com
                - name: SMTP_PASSWORD
                  value: mpvq mixq svte hwlc
                - name: JWT_SECRET
                  value: cultpick-jwt-secret
              ports: "3001"
              build: pnpm prisma generate && pnpm build
              start: pnpm start:prod
              install: pnpm i
              buildenv: []
            context:
              git:
                url: https://github.com/${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: nest.js
